// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260410175451_SyncModel4")]
    partial class SyncModel4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AddOnDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("BillingProviderProductRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AddOnDefinitions");
                });

            modelBuilder.Entity("Domain.Entities.AddOnEntitlement", b =>
                {
                    b.Property<string>("AddOnId")
                        .HasColumnType("character varying(120)");

                    b.Property<string>("EntitlementKey")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("ValueMode")
                        .HasColumnType("integer");

                    b.HasKey("AddOnId", "EntitlementKey");

                    b.HasIndex("EntitlementKey");

                    b.ToTable("AddOnEntitlements");
                });

            modelBuilder.Entity("Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Changes")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Domain.Entities.BillingEventInbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContractVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime?>("EffectiveAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetPlanId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("TenantId", "SubscriptionId");

                    b.ToTable("BillingEventInboxes");
                });

            modelBuilder.Entity("Domain.Entities.EntitlementDefinition", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ValueType")
                        .HasColumnType("integer");

                    b.HasKey("Key");

                    b.ToTable("EntitlementDefinitions");

                    b.HasData(
                        new
                        {
                            Key = "feature.billing.invoices.read",
                            Category = 0,
                            CreatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultValue = "false",
                            Description = "Allows tenant users to read tenant-scoped billing invoice summaries.",
                            DisplayName = "Billing invoice list access",
                            IsActive = true,
                            UpdatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = 0
                        },
                        new
                        {
                            Key = "feature.billing.subscription.manage",
                            Category = 0,
                            CreatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultValue = "false",
                            Description = "Allows cancellation and reactivation actions for tenant subscriptions.",
                            DisplayName = "Billing subscription self-service management",
                            IsActive = true,
                            UpdatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = 0
                        },
                        new
                        {
                            Key = "feature.billing.plan.upgrade",
                            Category = 0,
                            CreatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultValue = "false",
                            Description = "Allows tenant billing managers to perform plan upgrades.",
                            DisplayName = "Billing plan upgrade flow",
                            IsActive = true,
                            UpdatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = 0
                        },
                        new
                        {
                            Key = "feature.analytics.audit_logs.read",
                            Category = 0,
                            CreatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultValue = "false",
                            Description = "Allows tenant users to access analytics-oriented audit log read surfaces.",
                            DisplayName = "Tenant analytics and audit visibility",
                            IsActive = true,
                            UpdatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = 0
                        },
                        new
                        {
                            Key = "feature.admin.advanced.user_management",
                            Category = 0,
                            CreatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultValue = "false",
                            Description = "Allows privileged tenant administrators to access advanced user management capabilities.",
                            DisplayName = "Advanced tenant user management",
                            IsActive = true,
                            UpdatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = 0
                        },
                        new
                        {
                            Key = "feature.modules.future.hooks",
                            Category = 0,
                            CreatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultValue = "false",
                            Description = "Reserved module-level gate to support progressive rollout for future protected modules.",
                            DisplayName = "Future module gating hook",
                            IsActive = true,
                            UpdatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = 0
                        },
                        new
                        {
                            Key = "quota.api.calls.monthly",
                            Category = 1,
                            CreatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultValue = "0",
                            Description = "Plan-level monthly API call quota baseline.",
                            DisplayName = "Monthly API call quota",
                            IsActive = true,
                            UpdatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = 1
                        },
                        new
                        {
                            Key = "quota.users.max",
                            Category = 1,
                            CreatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultValue = "1",
                            Description = "Plan-level max allowed tenant users.",
                            DisplayName = "Maximum tenant users",
                            IsActive = true,
                            UpdatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "UserId", "UsedAt");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "View tenant data",
                            Name = "tenants.read"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Manage tenant settings",
                            Name = "tenants.manage"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "View tenant users",
                            Name = "users.read"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "Manage tenant users",
                            Name = "users.manage"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Description = "Manage billing",
                            Name = "billing.manage"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "View tenant audit logs",
                            Name = "auditlogs.read"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Plan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("ApiCallsPerMonth")
                        .HasColumnType("integer");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("integer");

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = "plan-free",
                            ApiCallsPerMonth = 1000,
                            DisplayOrder = 1,
                            IsActive = true,
                            MaxUsers = 1,
                            MonthlyPrice = 0m,
                            Name = "Free"
                        },
                        new
                        {
                            Id = "plan-pro",
                            ApiCallsPerMonth = 50000,
                            DisplayOrder = 2,
                            IsActive = true,
                            MaxUsers = 10,
                            MonthlyPrice = 99m,
                            Name = "Pro"
                        });
                });

            modelBuilder.Entity("Domain.Entities.PlanEntitlement", b =>
                {
                    b.Property<string>("PlanId")
                        .HasColumnType("text");

                    b.Property<string>("EntitlementKey")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("PlanId", "EntitlementKey");

                    b.HasIndex("EntitlementKey");

                    b.ToTable("PlanEntitlements");

                    b.HasData(
                        new
                        {
                            PlanId = "plan-free",
                            EntitlementKey = "feature.billing.invoices.read",
                            CreatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Source = 0,
                            UpdatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "true"
                        },
                        new
                        {
                            PlanId = "plan-pro",
                            EntitlementKey = "feature.billing.invoices.read",
                            CreatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Source = 0,
                            UpdatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "true"
                        },
                        new
                        {
                            PlanId = "plan-free",
                            EntitlementKey = "feature.billing.subscription.manage",
                            CreatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Source = 0,
                            UpdatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "true"
                        },
                        new
                        {
                            PlanId = "plan-pro",
                            EntitlementKey = "feature.billing.subscription.manage",
                            CreatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Source = 0,
                            UpdatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "true"
                        },
                        new
                        {
                            PlanId = "plan-free",
                            EntitlementKey = "feature.billing.plan.upgrade",
                            CreatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Source = 0,
                            UpdatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "true"
                        },
                        new
                        {
                            PlanId = "plan-pro",
                            EntitlementKey = "feature.billing.plan.upgrade",
                            CreatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Source = 0,
                            UpdatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "true"
                        },
                        new
                        {
                            PlanId = "plan-free",
                            EntitlementKey = "feature.analytics.audit_logs.read",
                            CreatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Source = 0,
                            UpdatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "true"
                        },
                        new
                        {
                            PlanId = "plan-pro",
                            EntitlementKey = "feature.analytics.audit_logs.read",
                            CreatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Source = 0,
                            UpdatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "true"
                        },
                        new
                        {
                            PlanId = "plan-free",
                            EntitlementKey = "feature.admin.advanced.user_management",
                            CreatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Source = 0,
                            UpdatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "true"
                        },
                        new
                        {
                            PlanId = "plan-pro",
                            EntitlementKey = "feature.admin.advanced.user_management",
                            CreatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Source = 0,
                            UpdatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "true"
                        },
                        new
                        {
                            PlanId = "plan-free",
                            EntitlementKey = "feature.modules.future.hooks",
                            CreatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Source = 0,
                            UpdatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "true"
                        },
                        new
                        {
                            PlanId = "plan-pro",
                            EntitlementKey = "feature.modules.future.hooks",
                            CreatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Source = 0,
                            UpdatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "true"
                        },
                        new
                        {
                            PlanId = "plan-free",
                            EntitlementKey = "quota.api.calls.monthly",
                            CreatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Source = 0,
                            UpdatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "1000"
                        },
                        new
                        {
                            PlanId = "plan-pro",
                            EntitlementKey = "quota.api.calls.monthly",
                            CreatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Source = 0,
                            UpdatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "50000"
                        },
                        new
                        {
                            PlanId = "plan-free",
                            EntitlementKey = "quota.users.max",
                            CreatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Source = 0,
                            UpdatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "1"
                        },
                        new
                        {
                            PlanId = "plan-pro",
                            EntitlementKey = "quota.users.max",
                            CreatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Source = 0,
                            UpdatedUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "10"
                        });
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "UserId", "ExpiresAt");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CanceledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CurrentPeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("GracePeriodEndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ScheduledPlanEffectiveAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScheduledPlanId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Subdomain")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Domain.Entities.TenantAddOnAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddOnId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveToUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AddOnId");

                    b.HasIndex("TenantId", "AddOnId", "Status");

                    b.HasIndex("TenantId", "Status", "EffectiveFromUtc");

                    b.ToTable("TenantAddOnAssignments");
                });

            modelBuilder.Entity("Domain.Entities.TenantEntitlementOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveToUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntitlementKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("EntitlementKey");

                    b.HasIndex("TenantId", "EntitlementKey", "EffectiveFromUtc");

                    b.ToTable("TenantEntitlementOverrides");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MfaEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("MfaEnabledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MfaSecret")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.UserInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RbacRoleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("TenantId", "Email", "AcceptedAt");

                    b.ToTable("UserInvites");
                });

            modelBuilder.Entity("Domain.Entities.UserMfaEnrollmentChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnrollmentTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentTokenHash")
                        .IsUnique();

                    b.HasIndex("TenantId", "UserId", "ExpiresAt");

                    b.ToTable("UserMfaEnrollmentChallenges");
                });

            modelBuilder.Entity("Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TenantId", "UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Domain.Entities.UserStepUpSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SessionTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionTokenHash")
                        .IsUnique();

                    b.HasIndex("TenantId", "UserId", "Purpose", "ExpiresAt");

                    b.ToTable("UserStepUpSessions");
                });

            modelBuilder.Entity("Domain.Entities.UserVerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "UserId", "UsedAt");

                    b.ToTable("UserVerificationTokens");
                });

            modelBuilder.Entity("Domain.Entities.AddOnEntitlement", b =>
                {
                    b.HasOne("Domain.Entities.AddOnDefinition", "AddOn")
                        .WithMany("Entitlements")
                        .HasForeignKey("AddOnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.EntitlementDefinition", "EntitlementDefinition")
                        .WithMany()
                        .HasForeignKey("EntitlementKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddOn");

                    b.Navigation("EntitlementDefinition");
                });

            modelBuilder.Entity("Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.PlanEntitlement", b =>
                {
                    b.HasOne("Domain.Entities.EntitlementDefinition", "EntitlementDefinition")
                        .WithMany("PlanEntitlements")
                        .HasForeignKey("EntitlementKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntitlementDefinition");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany("Roles")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.Subscription", b =>
                {
                    b.HasOne("Domain.Entities.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithOne("Subscription")
                        .HasForeignKey("Domain.Entities.Subscription", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Domain.Entities.TenantAddOnAssignment", b =>
                {
                    b.HasOne("Domain.Entities.AddOnDefinition", "AddOn")
                        .WithMany()
                        .HasForeignKey("AddOnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddOn");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Domain.Entities.TenantEntitlementOverride", b =>
                {
                    b.HasOne("Domain.Entities.EntitlementDefinition", "EntitlementDefinition")
                        .WithMany()
                        .HasForeignKey("EntitlementKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntitlementDefinition");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Domain.Entities.UserInvite", b =>
                {
                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany("UserRoles")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.UserVerificationToken", b =>
                {
                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.AddOnDefinition", b =>
                {
                    b.Navigation("Entitlements");
                });

            modelBuilder.Entity("Domain.Entities.EntitlementDefinition", b =>
                {
                    b.Navigation("PlanEntitlements");
                });

            modelBuilder.Entity("Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Domain.Entities.Tenant", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("Roles");

                    b.Navigation("Subscription");

                    b.Navigation("UserRoles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
